#
# Application
#

com.liferay.marketplace.spring.boot.url=

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-marketplace-etc-spring-boot-oauth-application-headless-server.oauth2.headless.server.client.secret=myfancypassword
liferay.oauth.application.external.reference.codes=liferay-marketplace-etc-cron-oauth-application-headless-server