##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.component.names ~ "Upgrades WEM") AND \
        (testray.main.component.name == "URL Redirections")

##
## Testray
##

    testray.main.component.name=URL Redirections