export enum Colors {
	Main = 'main',
	MainLighten4 = 'mainLighten4',
	MainLighten8 = 'mainLighten8',
	MainLighten28 = 'mainLighten28',
	MainLighten52 = 'mainLighten52',
	MainLighten65 = 'mainLighten65',
	MainLighten74 = 'mainLighten74',
	Secondary = 'secondary',
	SecondaryHover = 'secondaryHover',
	Primary = 'primary',
	PrimaryDarken5 = 'primaryDarken5',
	PrimaryDarken10 = 'primaryDarken10',
	PrimaryLighten23 = 'primaryLighten23',
	PrimaryLighten33 = 'primaryLighten33',
	PrimaryLighten45 = 'primaryLighten45',
	White = 'white',
	Black = 'black',
	LightBackground = 'lightBackground',
	Error = 'error',
	ErrorLighten28 = 'errorLighten28',
	ErrorLighten50 = 'errorLighten50',
	Success = 'success',
	SuccessLighten25 = 'successLighten25',
	SuccessLighten63 = 'successLighten63',
	Warning = 'warning',
	WarningLighten25 = 'warningLighten25',
	WarningLighten60 = 'warningLighten60',
	Info = 'info',
	InfoLighten28 = 'infoLighten28',
	InfoLighten53 = 'infoLighten53'
}

export type Size = 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | 'xxxl';
