const GeoMapLangKey = {
	Afghanistan: Liferay.Language.get('country.afghanistan'),
	Albania: Liferay.Language.get('country.albania'),
	Algeria: Liferay.Language.get('country.algeria'),
	Angola: Liferay.Language.get('country.angola'),
	Argentina: Liferay.Language.get('country.argentina'),
	Armenia: Liferay.Language.get('country.armenia'),
	Australia: Liferay.Language.get('country.australia'),
	Austria: Liferay.Language.get('country.austria'),
	Azerbaijan: Liferay.Language.get('country.azerbaijan'),
	Bahamas: Liferay.Language.get('country.bahamas'),
	Bangladesh: Liferay.Language.get('country.bangladesh'),
	Belarus: Liferay.Language.get('country.belarus'),
	Belgium: Liferay.Language.get('country.belgium'),
	Belize: Liferay.Language.get('country.belize'),
	Benin: Liferay.Language.get('country.benin'),
	Bermuda: Liferay.Language.get('country.bermuda'),
	Bhutan: Liferay.Language.get('country.bhutan'),
	Bolivia: Liferay.Language.get('country.bolivia'),
	'Bosnia and Herzegovina': Liferay.Language.get(
		'country.bosnia-herzegovina'
	),
	Botswana: Liferay.Language.get('country.botswana'),
	Brazil: Liferay.Language.get('country.brazil'),
	'Brunei Darussalam': Liferay.Language.get('country.brunei'),
	Bulgaria: Liferay.Language.get('country.bulgaria'),
	'Burkina Faso': Liferay.Language.get('country.burkina-faso'),
	Burundi: Liferay.Language.get('country.burundi'),
	Cambodia: Liferay.Language.get('country.cambodia'),
	Cameroon: Liferay.Language.get('country.cameroon'),
	Canada: Liferay.Language.get('country.canada'),
	'Central African Republic': Liferay.Language.get(
		'country.central-african-republic'
	),
	Chad: Liferay.Language.get('country.chad'),
	Chile: Liferay.Language.get('country.chile'),
	China: Liferay.Language.get('country.china'),
	Colombia: Liferay.Language.get('country.colombia'),
	Congo: Liferay.Language.get('country.republic-of-congo'),
	'Congo, the Democratic Republic of the': Liferay.Language.get(
		'country.democratic-republic-of-congo'
	),
	'Costa Rica': Liferay.Language.get('country.costa-rica'),
	"Cote D'ivoire": Liferay.Language.get('country.cote-divoire'),
	Croatia: Liferay.Language.get('country.croatia'),
	Cuba: Liferay.Language.get('country.cuba'),
	Cyprus: Liferay.Language.get('country.cyprus'),
	'Czech Republic': Liferay.Language.get('country.czech-republic'),
	Denmark: Liferay.Language.get('country.denmark'),
	Djibouti: Liferay.Language.get('country.djibouti'),
	'Dominican Republic': Liferay.Language.get('country.dominican-republic'),
	Ecuador: Liferay.Language.get('country.ecuador'),
	Egypt: Liferay.Language.get('country.egypt'),
	'El Salvador': Liferay.Language.get('country.el-salvador'),
	'Equatorial Guinea': Liferay.Language.get('country.equatorial-guinea'),
	Eritrea: Liferay.Language.get('country.eritrea'),
	Estonia: Liferay.Language.get('country.estonia'),
	Ethiopia: Liferay.Language.get('country.ethiopia'),
	'Falkland Islands': Liferay.Language.get('country.falkland-islands'),
	Fiji: Liferay.Language.get('country.fiji-islands'),
	Finland: Liferay.Language.get('country.finland'),
	France: Liferay.Language.get('country.france'),
	'French Guiana': Liferay.Language.get('country.french-guiana'),
	'French Southern and Antarctic Lands': Liferay.Language.get(
		'country.french-southern-territories'
	),
	Gabon: Liferay.Language.get('country.gabon'),
	Gambia: Liferay.Language.get('country.gambia'),
	Georgia: Liferay.Language.get('country.georgia'),
	Germany: Liferay.Language.get('country.germany'),
	Ghana: Liferay.Language.get('country.ghana'),
	Greece: Liferay.Language.get('country.greece'),
	Greenland: Liferay.Language.get('country.greenland'),
	Guatemala: Liferay.Language.get('country.guatemala'),
	Guinea: Liferay.Language.get('country.guinea'),
	'Guinea Bissau': Liferay.Language.get('country.guinea-bissau'),
	Guyana: Liferay.Language.get('country.guyana'),
	Haiti: Liferay.Language.get('country.haiti'),
	Honduras: Liferay.Language.get('country.honduras'),
	Hungary: Liferay.Language.get('country.hungary'),
	Iceland: Liferay.Language.get('country.iceland'),
	India: Liferay.Language.get('country.india'),
	Indonesia: Liferay.Language.get('country.indonesia'),
	'Iran, Islamic Republic of': Liferay.Language.get('country.iran'),
	Iraq: Liferay.Language.get('country.iraq'),
	Ireland: Liferay.Language.get('country.ireland'),
	Israel: Liferay.Language.get('country.israel'),
	Italy: Liferay.Language.get('country.italy'),
	Jamaica: Liferay.Language.get('country.jamaica'),
	Japan: Liferay.Language.get('country.japan'),
	Jordan: Liferay.Language.get('country.jordan'),
	Kazakhstan: Liferay.Language.get('country.kazakhstan'),
	Kenya: Liferay.Language.get('country.kenya'),
	'Korea, Republic of': Liferay.Language.get('country.south-korea'),
	Kosovo: Liferay.Language.get('country.kosovo'),
	Kuwait: Liferay.Language.get('country.kuwait'),
	Kyrgyzstan: Liferay.Language.get('country.kyrgyzstan'),
	"Lao People's Democratic Republic": Liferay.Language.get(
		'country.lao-peoples-democratic-republic'
	),
	Latvia: Liferay.Language.get('country.latvia'),
	Lebanon: Liferay.Language.get('country.lebanon'),
	Lesotho: Liferay.Language.get('country.lesotho'),
	Liberia: Liferay.Language.get('country.liberia'),
	Libya: Liferay.Language.get('country.libya'),
	Lithuania: Liferay.Language.get('country.lithuania'),
	Luxembourg: Liferay.Language.get('country.luxembourg'),
	Macedonia: Liferay.Language.get('country.macedonia'),
	Madagascar: Liferay.Language.get('country.madagascar'),
	Malawi: Liferay.Language.get('country.malawi'),
	Malaysia: Liferay.Language.get('country.malaysia'),
	Mali: Liferay.Language.get('country.mali'),
	Malta: Liferay.Language.get('country.malta'),
	Mauritania: Liferay.Language.get('country.mauritania'),
	Mexico: Liferay.Language.get('country.mexico'),
	'Moldova, Republic of': Liferay.Language.get('country.moldova'),
	Mongolia: Liferay.Language.get('country.mongolia'),
	Montenegro: Liferay.Language.get('country.montenegro'),
	Morocco: Liferay.Language.get('country.morocco'),
	Mozambique: Liferay.Language.get('country.mozambique'),
	Myanmar: Liferay.Language.get('country.burma-myanmar'),
	Namibia: Liferay.Language.get('country.namibia'),
	Nepal: Liferay.Language.get('country.nepal'),
	Netherlands: Liferay.Language.get('country.netherlands'),
	'New Caledonia': Liferay.Language.get('country.new-caledonia'),
	'New Zealand': Liferay.Language.get('country.new-zealand'),
	Nicaragua: Liferay.Language.get('country.nicaragua'),
	Niger: Liferay.Language.get('country.niger'),
	Nigeria: Liferay.Language.get('country.nigeria'),
	'North Korea': Liferay.Language.get('country.north-korea'),
	'Northern Cyprus': Liferay.Language.get('country.northern-cyprus'),
	Norway: Liferay.Language.get('country.norway'),
	Oman: Liferay.Language.get('country.oman'),
	Pakistan: Liferay.Language.get('country.pakistan'),
	'Palestinian Territory': Liferay.Language.get(
		'country.palestinian-territory'
	),
	Panama: Liferay.Language.get('country.panama'),
	'Papua New Guinea': Liferay.Language.get('country.papua-new-guinea'),
	Paraguay: Liferay.Language.get('country.paraguay'),
	Peru: Liferay.Language.get('country.peru'),
	Philippines: Liferay.Language.get('country.philippines'),
	Poland: Liferay.Language.get('country.poland'),
	Portugal: Liferay.Language.get('country.portugal'),
	'Puerto Rico': Liferay.Language.get('country.puerto-rico'),
	Qatar: Liferay.Language.get('country.qatar'),
	Romania: Liferay.Language.get('country.romania'),
	'Russian Federation': Liferay.Language.get('country.russia'),
	Rwanda: Liferay.Language.get('country.rwanda'),
	'Saudi Arabia': Liferay.Language.get('country.saudi-arabia'),
	Senegal: Liferay.Language.get('country.senegal'),
	Serbia: Liferay.Language.get('country.serbia'),
	'Sierra Leone': Liferay.Language.get('country.sierra-leone'),
	Slovakia: Liferay.Language.get('country.slovakia'),
	Slovenia: Liferay.Language.get('country.slovenia'),
	'Solomon Islands': Liferay.Language.get('country.solomon-islands'),
	Somalia: Liferay.Language.get('country.somalia'),
	Somaliland: Liferay.Language.get('country.somaliland'),
	'South Africa': Liferay.Language.get('country.south-africa'),
	'South Sudan': Liferay.Language.get('country.south-sudan'),
	Spain: Liferay.Language.get('country.spain'),
	'Sri Lanka': Liferay.Language.get('country.sri-lanka'),
	Sudan: Liferay.Language.get('country.sudan'),
	Suriname: Liferay.Language.get('country.suriname'),
	Swaziland: Liferay.Language.get('country.swaziland'),
	Sweden: Liferay.Language.get('country.sweden'),
	Switzerland: Liferay.Language.get('country.switzerland'),
	'Syrian Arab Republic': Liferay.Language.get(
		'country.syrian-arab-republic'
	),
	Taiwan: Liferay.Language.get('country.taiwan'),
	Tajikistan: Liferay.Language.get('country.tajikistan'),
	'Tanzania, United Republic of': Liferay.Language.get('country.tanzania'),
	Thailand: Liferay.Language.get('country.thailand'),
	'Timor-Leste': Liferay.Language.get('country.timor-leste'),
	Togo: Liferay.Language.get('country.togo'),
	'Trinidad and Tobago': Liferay.Language.get('country.trinidad-tobago'),
	Tunisia: Liferay.Language.get('country.tunisia'),
	Turkey: Liferay.Language.get('country.turkey'),
	Turkmenistan: Liferay.Language.get('country.turkmenistan'),
	Uganda: Liferay.Language.get('country.uganda'),
	Ukraine: Liferay.Language.get('country.ukraine'),
	'United Arab Emirates': Liferay.Language.get(
		'country.united-arab-emirates'
	),
	'United Kingdom': Liferay.Language.get('country.united-kingdom'),
	'United States': Liferay.Language.get('country.united-states'),
	Uruguay: Liferay.Language.get('country.uruguay'),
	Uzbekistan: Liferay.Language.get('country.uzbekistan'),
	Vanuatu: Liferay.Language.get('country.vanuatu'),
	Venezuela: Liferay.Language.get('country.venezuela'),
	Vietnam: Liferay.Language.get('country.vietnam'),
	'Western Sahara': Liferay.Language.get('country.western-sahara'),
	Yemen: Liferay.Language.get('country.yemen'),
	Zambia: Liferay.Language.get('country.zambia'),
	Zimbabwe: Liferay.Language.get('country.zimbabwe')
};

export default GeoMapLangKey;
