/**
 * SPDX-FileCopyrightText: [(c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: [LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

module.exports = {
	exports: [
		'html-to-image',
		'jspdf',
		'@liferay/js-api',
		'@liferay/js-api/data-set',
		'cropperjs/dist/cropper.css',
		'date-fns',
		'graphql-hooks-memcache',
		'graphql-hooks',
		'graphql',
		'highlight.js/styles/monokai-sublime.css',
		'qrcode',
		'react-dropzone',
		'react-transition-group',
		'uuid',
		'react-flow-renderer',
		'react-helmet',
		'react-router-dom',
		'graphiql',
		'graphiql/graphiql.css',
		'axe-core',
		'clipboard',
		'cropperjs',
		'dagre',
		'dom-align',
		'fuzzy',
		'highlight.js',
		'highlight.js/lib/core',
		'highlight.js/lib/languages/java',
		'highlight.js/lib/languages/javascript',
		'highlight.js/lib/languages/plaintext',
		'image-promise',
		'liferay-ckeditor',
		'lodash.groupby',
		'lodash.isequal',
		'moment',
		'moment/min/moment-with-locales',
		'numeral',
		'object-hash',
		'pkce-challenge',
		'qs',
		'react-text-mask',
		'text-mask-addons',
		'text-mask-core',
	],
};
