#
# Application
#

liferay.customer.etc.spring.boot.client.extension.url=http://localhost:58081
liferay.customer.zendesk.ticket.closed.days=30
liferay.osb.spring.boot.client.zendesk.api.token=
liferay.osb.spring.boot.client.zendesk.api.email.address=
liferay.osb.spring.boot.client.zendesk.url=

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-cron-oauth-application-headless-server,\
    liferay-customer-etc-spring-boot-oauth-application-headless-server