##
## Modules
##

    modules.includes.required.functional[relevant]=\
        apps/document-library,\
        apps/fragment,\
        apps/segments

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant]=\
        apps/document-library/**/src/test/**/*Test.java,\
        apps/fragment/**/src/test/**/*Test.java\
        apps/segments/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-integration-*-jdk8][relevant]=\
        apps/document-library/**/src/testIntegration/**/*Test.java,\
        apps/fragment/**/src/testIntegration/**/*Test.java,\
        apps/segments/**/src/testIntegration/**/*Test.java

##
## Test Batch
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Auto Tagging") OR \
            (testray.component.names ~ "Categories") OR \
            (testray.component.names ~ "Collections") OR \
            (testray.main.component.name ~ "Asset Publisher Widget") OR \
            (testray.main.component.name ~ "Auto Tagging") OR \
            (testray.main.component.name ~ "Categories") OR \
            (testray.main.component.name ~ "Collections") OR \
            (testray.main.component.name ~ "Display Page Templates") OR \
            (testray.main.component.name ~ "Fragment Administration") OR \
            (testray.main.component.name ~ "Localization") OR \
            (testray.main.component.name ~ "Message Boards") OR \
            (testray.main.component.name ~ "Recycle Bin") OR \
            (testray.main.component.name ~ "Related Assets Widget") OR \
            (testray.main.component.name ~ "Tags")\
        )

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (testray.component.names ~ "Upgrades WEM")