/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export enum MDFColumnKey {
	ACCOUNT_ENTRY_ID = 'ACCOUNT_ENTRY_ID',
	ACTION = 'FIXED_ACTION',
	ACTIVITY_PERIOD = 'ACTIVITY_PERIOD',
	AMOUNT_CLAIMED = 'AMOUNT_CLAIMED',
	AMOUNT_PAID = 'AMOUNT_PAID',
	APPROVED = 'APPROVED',
	BALANCE = 'BALANCE',
	CAMPAIGN_NAME = 'CAMPAIGN_NAME',
	DATE_SUBMITTTED = 'DATE_SUBMITTED',
	ID = 'REQUEST_ID',
	LAST_MODIFIED = 'LAST_MODIFIED',
	PARTNER = 'PARTNER',
	REQUEST_STATUS = 'REQUEST_STATUS',
	REQUESTED = 'REQUESTED',
	TOTAL_COST = 'TOTAL_COST',
}
