##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.component.names == "Wiki") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Testray
##

    testray.main.component.name=Wiki