#
# Application
#

liferay.customer.gcs.bucket.name=
liferay.customer.gcs.service.account.key=
liferay.osb.spring.boot.client.zendesk.api.email.address=
liferay.osb.spring.boot.client.zendesk.api.token=
liferay.osb.spring.boot.client.zendesk.url=

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-spring-boot-oauth-application-headless-server,\
    liferay-customer-etc-spring-boot-oauth-application-user-agent
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081