/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PermissionCheckFinderEntry service. Represents a row in the &quot;PermissionCheckFinderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.PermissionCheckFinderEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.PermissionCheckFinderEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionCheckFinderEntry
 * @generated
 */
@ProviderType
public interface PermissionCheckFinderEntryModel
	extends BaseModel<PermissionCheckFinderEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permission check finder entry model instance should use the {@link PermissionCheckFinderEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this permission check finder entry.
	 *
	 * @return the primary key of this permission check finder entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permission check finder entry.
	 *
	 * @param primaryKey the primary key of this permission check finder entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the permission check finder entry ID of this permission check finder entry.
	 *
	 * @return the permission check finder entry ID of this permission check finder entry
	 */
	public long getPermissionCheckFinderEntryId();

	/**
	 * Sets the permission check finder entry ID of this permission check finder entry.
	 *
	 * @param permissionCheckFinderEntryId the permission check finder entry ID of this permission check finder entry
	 */
	public void setPermissionCheckFinderEntryId(
		long permissionCheckFinderEntryId);

	/**
	 * Returns the group ID of this permission check finder entry.
	 *
	 * @return the group ID of this permission check finder entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this permission check finder entry.
	 *
	 * @param groupId the group ID of this permission check finder entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the integer of this permission check finder entry.
	 *
	 * @return the integer of this permission check finder entry
	 */
	public int getInteger();

	/**
	 * Sets the integer of this permission check finder entry.
	 *
	 * @param integer the integer of this permission check finder entry
	 */
	public void setInteger(int integer);

	/**
	 * Returns the name of this permission check finder entry.
	 *
	 * @return the name of this permission check finder entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this permission check finder entry.
	 *
	 * @param name the name of this permission check finder entry
	 */
	public void setName(String name);

	/**
	 * Returns the type of this permission check finder entry.
	 *
	 * @return the type of this permission check finder entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this permission check finder entry.
	 *
	 * @param type the type of this permission check finder entry
	 */
	public void setType(String type);

	@Override
	public PermissionCheckFinderEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}