/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export const CREATE_SEGMENTS_EXPERIENCE = 'CREATE_SEGMENTS_EXPERIENCE';
export const SELECT_SEGMENTS_EXPERIENCE = 'SELECT_SEGMENTS_EXPERIENCE';
export const DELETE_SEGMENTS_EXPERIENCE = 'DELETE_SEGMENTS_EXPERIENCE';
export const UPDATE_SEGMENTS_EXPERIENCE = 'UPDATE_SEGMENTS_EXPERIENCE';
export const UPDATE_SEGMENTS_EXPERIENCES_LIST =
	'UPDATE_SEGMENTS_EXPERIENCES_LIST';
