/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.dynamic.data.mapping.configuration;

import aQute.bnd.annotation.metatype.Meta;

import com.liferay.portal.configuration.metatype.annotations.ExtendedObjectClassDefinition;

/**
 * @author Lino Alves
 */
@ExtendedObjectClassDefinition(category = "dynamic-data-mapping")
@Meta.OCD(
	id = "com.liferay.dynamic.data.mapping.configuration.DDMWebConfiguration",
	localization = "content/Language", name = "ddmweb-configuration-name"
)
public interface DDMWebConfiguration {

	/**
	 * Returns <code>true</code> if dynamic data mapping structure keys should
	 * always be autogenerated.
	 *
	 * @return <code>true</code> if dynamic data mapping structure keys should
	 *         always be autogenerated; <code>false</code> otherwise
	 */
	@Meta.AD(
		deflt = "true",
		description = "check-this-if-dynamic-data-mapping-structure-keys-should-always-be-autogenerated",
		name = "autogenerate-structure-key", required = false
	)
	public boolean autogenerateStructureKey();

	/**
	 * Returns <code>true</code> if dynamic data mapping template keys should
	 * always be autogenerated.
	 *
	 * @return <code>true</code> if dynamic data mapping template keys should
	 *         always be autogenerated; <code>false</code> otherwise
	 */
	@Meta.AD(
		deflt = "true",
		description = "check-this-if-dynamic-data-mapping-template-keys-should-always-be-autogenerated",
		name = "autogenerate-template-key", required = false
	)
	public boolean autogenerateTemplateKey();

	@Meta.AD(
		deflt = "false",
		description = "if-checked,-the-default-language-of-dynamic-data-mapping-structures-will-be-changeable",
		name = "changeable-default-language", required = false
	)
	public boolean changeableDefaultLanguage();

	@Meta.AD(
		deflt = "true", description = "enable-template-creation-description",
		name = "enable-template-creation", required = false
	)
	public boolean enableTemplateCreation();

}