/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export declare const ADD_FRAGMENT_COMPOSITION = 'ADD_FRAGMENT_COMPOSITION';
export declare const ADD_FRAGMENT_ENTRY_LINKS = 'ADD_FRAGMENT_ENTRY_LINKS';
export declare const ADD_FRAGMENT_ENTRY_LINK_COMMENT =
	'ADD_FRAGMENT_ENTRY_LINK_COMMENT';
export declare const ADD_ITEM = 'ADD_ITEM';
export declare const ADD_MAPPED_INFO_ITEM = 'ADD_MAPPED_INFO_ITEM';
export declare const ADD_MAPPING_FIELDS = 'ADD_MAPPING_FIELDS';
export declare const ADD_REDO_ACTION = 'ADD_REDO_ACTION';
export declare const ADD_RULE = 'ADD_RULE';
export declare const ADD_UNDO_ACTION = 'ADD_UNDO_ACTION';
export declare const CHANGE_MASTER_LAYOUT = 'CHANGE_MASTER_LAYOUT';
export declare const DELETE_FRAGMENT_ENTRY_LINK_COMMENT =
	'DELETE_FRAGMENT_ENTRY_LINK_COMMENT';
export declare const DELETE_ITEM = 'DELETE_ITEM';
export declare const DELETE_RULE = 'DELETE_RULE';
export declare const DUPLICATE_ITEM = 'DUPLICATE_ITEM';
export declare const EDIT_FRAGMENT_ENTRY_LINK_COMMENT =
	'EDIT_FRAGMENT_ENTRY_LINK_COMMENT';
export declare const INIT = 'INIT';
export declare const LOAD_REDUCER = 'LOAD_REDUCER';
export declare const MOVE_ITEM = 'MOVE_ITEM';
export declare const SWITCH_SIDEBAR_PANEL = 'SWITCH_SIDEBAR_PANEL';
export declare const SWITCH_VIEWPORT_SIZE = 'SWITCH_VIEWPORT_SIZE';
export declare const TOGGLE_FRAGMENT_HIGHLIGHTED =
	'TOGGLE_FRAGMENT_HIGHLIGHTED';
export declare const TOGGLE_PERMISSION = 'TOGGLE_PERMISSION';
export declare const TOGGLE_SHOW_RESOLVED_COMMENTS =
	'TOGGLE_SHOW_RESOLVED_COMMENTS';
export declare const TOGGLE_WIDGET_HIGHLIGHTED = 'TOGGLE_WIDGET_HIGHLIGHTED';
export declare const UNLOAD_REDUCER = 'UNLOAD_REDUCER';
export declare const UPDATE_COL_SIZE = 'UPDATE_COL_SIZE';
export declare const UPDATE_COLLECTION_DISPLAY_COLLECTION =
	'UPDATE_COLLECTION_DISPLAY_COLLECTION';
export declare const UPDATE_DRAFT = 'UPDATE_DRAFT';
export declare const UPDATE_EDITABLE_VALUES = 'UPDATE_EDITABLE_VALUES';
export declare const UPDATE_ITEM_CONFIG = 'UPDATE_ITEM_CONFIG';
export declare const UPDATE_FORM_ITEM_CONFIG = 'UPDATE_FORM_ITEM_CONFIG';
export declare const UPDATE_FRAGMENT_ENTRY_LINK_CONFIGURATION =
	'UPDATE_FRAGMENT_ENTRY_LINK_CONFIGURATION';
export declare const UPDATE_FRAGMENT_ENTRY_LINK_CONTENT =
	'UPDATE_FRAGMENT_ENTRY_LINK_CONTENT';
export declare const UPDATE_FRAGMENT_ENTRY_LINKS_CONTENT =
	'UPDATE_FRAGMENT_ENTRY_LINKS_CONTENT';
export declare const UPDATE_FRAGMENTS = 'UPDATE_FRAGMENTS';
export declare const UPDATE_LANGUAGE_ID = 'UPDATE_LANGUAGE_ID';
export declare const UPDATE_NETWORK = 'UPDATE_NETWORK';
export declare const UPDATE_REDO_ACTIONS = 'UPDATE_REDO_ACTIONS';
export declare const UPDATE_ROW_COLUMNS = 'UPDATE_ROW_COLUMNS';
export declare const UPDATE_UNDO_ACTIONS = 'UPDATE_UNDO_ACTIONS';
export declare const UPDATE_PREVIEW_IMAGE = 'UPDATE_PREVIEW_IMAGE';
export declare const UPDATE_RULE = 'UPDATE_RULE';
export declare const UPDATE_WIDGETS = 'UPDATE_WIDGETS';
