/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {config} from 'dotenv';

config();

const {
	APP_DEBUG_CACHE_ROUTER = '/cache',
	JIRA_API_BASE_URL,
	JIRA_APP_FIELD_ID_QA_TEST_NAME,
	JIRA_APP_FIELD_ID_QA_TEST_SCORE,
	JIRA_APP_NAME,
	JIRA_AUTH_BASE_URL,
	JIRA_AUTH_CLIENT_ID,
	JIRA_AUTH_CLIENT_SECRET,
	JIRA_AUTH_CLOUD_ID,
	JIRA_AUTH_GRANT_TYPE,
	JIRA_AUTH_GRANT_TYPE_REFRESH_TOKEN,
	JIRA_AUTH_REDIRECT_URI,
	JIRA_AUTH_SCOPES,
	JIRA_AUTH_STATE_PREFIX,
	LIFERAY_AUTH_CLIENT_ID,
	LIFERAY_AUTH_CLIENT_SECRET,
	LIFERAY_AUTH_TOKEN,
	LIFERAY_BASE_URL,
	LIFERAY_TESTRAY_REDIRECT_AUTHORIZATION,
	PORT = 3001,
	PUSHER_APP_ID,
	PUSHER_APP_KEY,
	PUSHER_APP_REGION = 'sa1',
	PUSHER_APP_SECRET,
} = process.env;

export {
	APP_DEBUG_CACHE_ROUTER,
	JIRA_API_BASE_URL,
	JIRA_APP_FIELD_ID_QA_TEST_NAME,
	JIRA_APP_FIELD_ID_QA_TEST_SCORE,
	JIRA_APP_NAME,
	JIRA_AUTH_BASE_URL,
	JIRA_AUTH_CLIENT_ID,
	JIRA_AUTH_CLIENT_SECRET,
	JIRA_AUTH_CLOUD_ID,
	JIRA_AUTH_GRANT_TYPE,
	JIRA_AUTH_GRANT_TYPE_REFRESH_TOKEN,
	JIRA_AUTH_REDIRECT_URI,
	JIRA_AUTH_SCOPES,
	JIRA_AUTH_STATE_PREFIX,
	LIFERAY_AUTH_CLIENT_ID,
	LIFERAY_AUTH_CLIENT_SECRET,
	LIFERAY_AUTH_TOKEN,
	LIFERAY_BASE_URL,
	LIFERAY_TESTRAY_REDIRECT_AUTHORIZATION,
	PORT,
	PUSHER_APP_ID,
	PUSHER_APP_KEY,
	PUSHER_APP_REGION,
	PUSHER_APP_SECRET,
};
