##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant]=blogs-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.component.names == "Blogs") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Testray
##

    testray.main.component.name=Blogs